web-app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  get '/feedbacks/new'
  post '/feedbacks/create'
  get 'user_projects/index'

  resources :incubators
  post '/tinymce_assets' => 'tinymce_assets#create'

  devise_for :users
  ActiveAdmin.routes(self)

  resources :projects do
    resources :comments, module: :projects
    resources :project_members
    resources :mobilnik_payments do
      collection do
        get 'user_info_request'
        get 'admin_phone_number_request'
        get 'mobilnik_code_request'
        get 'mobilnik_token_request'
        get 'mobilnik_code_request_for_admin'
        get 'mobilnik_token_request_for_admin'
      end
    end
  end
  
  resources :categories
  resources :subscribed_mails
  resources :incubators
  
  authenticate :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'projects#index'
end

web-app/app/models/project.rb
class Project < ApplicationRecord
  self.send(:include, Kaminari::ConfigurationMethods)

  def self.page(num = nil)
    limit(default_per_page).offset(default_per_page * ((num = num.to_i - 1) < 0 ? 0 : num)).extending do
      include Kaminari::ActiveRecordRelationMethods
      include Kaminari::PageScopeMethods
    end
  end

  before_save :calculate_percent_of_budget_donated

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :project_members, dependent: :destroy
  has_many :subscribed_mails, dependent: :destroy
  accepts_nested_attributes_for :project_members, :reject_if => lambda {|a| a[:name].blank?}, :allow_destroy => true
  belongs_to :category

  has_attached_file :image,
                    styles: {medium: '400x400>', thumb: '300x300>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image,
                                    content_type: ['image/jpeg', 'image/gif', 'image/png']

  validates :image, presence: true
  validates :name, presence: true,
            uniqueness: true,
            length: {minimum: 1}
  validates :description, presence: true,
            length: {maximum: 5400}
  validates :budget, presence: true,
            numericality: {greater_than: 0}
  validates :budget_description, presence: true,
            length: {maximum: 3600}
  validates :budget_donated, presence: true,
            numericality: {greater_than_or_equal_to: 0}
  validates :stage, presence: true
  validates :account, presence: true,
            uniqueness: true
  validates :status, presence: true
  validates :deadline, presence: true
  validates :cancel_reason, length: {maximum: 1800}
  validates :author_comment, length: {maximum: 1800}
  validates :other_category, length: {maximum: 50}
  validates :category_id, presence: true
  validate :deadline_cannot_be_in_the_past
  validate :other_category_should_be_specified

  filterrific(
      default_filter_params: {with_status: 'Активный', sorted_by: 'donation_ratio_desc'},
      available_filters: [
          :sorted_by,
          :with_status,
          :with_category
      ]
  )

  def deadline_cannot_be_in_the_past
    if !deadline.blank? and deadline < Time.now and status == 'Активный'
      errors.add(:deadline, "can't be in the past")
    end
  end

  def other_category_should_be_specified
    if category_id == 3 and other_category.blank?
      errors.add(:other_category, "can't be blank")
    end
  end

# скоуп для выборки по статусу работает с gem 'filterrific'
  scope :with_status, lambda {|flag|
    where(status: [*flag])
  }
# скоуп для выборки по категориям работает с gem 'filterrific'
  scope :with_category, lambda {|category|
    where(category_id: [*category])}
# скоуп для сортировки всех проектор работает с gem 'filerrific'
  scope :sorted_by, lambda {|sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^donation_ratio_/
        # Simple sort on the created_at column.
        # Make sure to include the table name to avoid ambiguous column names.
        # Joining on other tables is quite common in Filterrific, and almost
        # every ActiveRecord table has a 'created_at' column.
        order("projects.donation_ratio #{ direction }")
      when /^deadline_/
        # Simple sort on the name colums
        order("projects.deadline #{ direction }")
      when /^created_at_/
        # This sorts by a student's country name, so we need to include
        # the country. We can't use JOIN since not all students might have
        # a country.
        order("projects.created_at #{ direction }")
      when /^rating_/
        # collect all comments and group by projtcts id and order by amaunt of comments
        Project.joins(:comments).group("projects.id").order("count(projects.id) #{ direction }")
        order("projects.click #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
        ['Дата создания (по убыванию)', 'created_at_desc'],
        ['Дата создания (по возрастанию', 'created_at_asc'],
        ['Сроку сбора (по возрастанию)', 'deadline_asc'],
        ['Сроку сбора (по убыванию)', 'deadline_desc'],
        ['По сбору денег (по возрастанию)', 'donation_ratio_asc'],
        ['По сбору денег (по убыванию)', 'donation_ratio_desc'],
        ['Популярность (по убыванию)', 'rating_desc'],
        ['Популярность (по возрастанию)', 'rating_asc']
    ]
  end

  private
  def calculate_percent_of_budget_donated
    self.donation_ratio = ((self.budget_donated.to_f*100)/self.budget.to_f).round()
  end

end

web-app/app/controllers/projects/comments_controller.rb
class Projects::CommentsController < CommentsController
	before_action :set_commentable, only: [:new, :create, :edit, :update, :destroy]

	private
	  def set_commentable
	  	@commentable = Project.find(params[:project_id])
	  end
end

web-app/app/controllers/projects_controller.rb
require 'builder'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  layout 'index_layout', only: [:index]

  def index

    @filterrific = initialize_filterrific(Project, params[:filterrific])
    @filterrific.select_options = {
        sorted_by: Project.options_for_sorted_by
    }
    @projects = Project.filterrific_find(@filterrific).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    change_project_status(@project)
    click_counter(@project)
    @subscribed_mail = SubscribedMail.new

  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
    authorize @project
    assign_other_category_name(@project)
    @project.cancel_date = @project.deadline

    respond_to do |format|
      if @project.save
        format.html {redirect_to root_path, notice: 'Project was successfully created.'}
        format.json {render :show, status: :created, location: @project}
      else
        format.html {render :new}
        format.json {render json: @project.errors, status: :unprocessable_entity}
      end
    end

  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project
    respond_to do |format|
      if @project.update(project_params)
        format.html {redirect_to @project, notice: 'Project was successfully updated.'}
        format.json {render :show, status: :ok, location: @project}
      else
        format.html {render :edit}
        format.json {render json: @project.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project
    @project.destroy
    respond_to do |format|
      format.html {redirect_to projects_url, notice: 'Project was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def change_project_status(project)
    if project.deadline <= Time.now or project.cancel_date <=Time.now
      project.status = 'Неактивный'
    else
      project.status = 'Активный'
    end
  end

  def assign_other_category_name(project)
    if project.category_id == Category.find_by(name: 'Другое').id
      @category_other = Category.create(name: project.other_category)
      project.category_id = @category_other.id
    end
  end
  def click_counter(project)
    project.update(click: (project.click + 1))
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :budget, :budget_description, :budget_donated, :stage, :account, :status, :deadline, :cancel_date, :cancel_reason, :author_comment, :other_category, :category_id, :image, :file)
  end
end

web-app/app/helpers/projects_helper.rb
module ProjectsHelper
  def number_of_days_till_deadline(project)
    ((Time.at(project.deadline - Time.now)).utc).strftime("%m месяца %d дней %H часов %M минут")
  end

  def subscribed_email?(project)
    emails = project.subscribed_mails
    result = nil
    emails.each do |subscriber|
      if current_user.email == subscriber.email
        result = true
      else
        result = false
      end
    end
    return result
  end
  def email_unsubscribe
    SubscribedMail.all.each do |subscriber|
      if subscriber.email == current_user.email
        return subscriber.id
      end
    end
  end
  
  def nested_comments(comments, project)
    comments.map do |comment, sub_comments|
      render(:template => "comments/_comment", :locals => {:comment => comment, :commentable => project}) + content_tag(:div, nested_comments(sub_comments,project), class: ["nested_comments"])
    end.join.html_safe
  end
end

web-app/app/views/projects/_form.html.erb
<div class = 'container'>
  <div class = 'row'>
    <div class ='col-md-6 col-md-offset-3'>
      <%= simple_form_for(@project) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description, :input_html => {:class => 'tinymce', :rows => 20, :cols => 120} %>
            <%= f.input :budget %>
            <%= f.input :budget_description, :input_html => {:class => 'tinymce', :rows => 20, :cols => 120} %>
            <%= f.input :budget_donated %>
            <%= f.input :stage, collection: [ "Идея", "Препроект", "В разработке", "Прототип"]%>
            <%= f.input :account %>
            <%= f.input :status, collection: ["Активный", "Неактивный"] %>
            <%= f.input :deadline %>
            <%= f.input :cancel_date %>
            <%= f.input :cancel_reason, :input_html => {:class => 'tinymce', :rows => 20, :cols => 120} %>
            <%= f.input :author_comment, :input_html => {:class => 'tinymce', :rows => 20, :cols => 120} %>
            <%= f.association :category %>
            <%= f.input :other_category %>
            <%= f.file_field :image %>
          </div>
          <div class="form-actions">
            <%= f.button :submit %>
          </div>
    <% end %>
    </div>
  </div>
</div>

<%= tinymce %>

web-app/app/views/projects/_list.html.erb
<div class="row crowdfunding_projects">
  <% projects.each do |project| %>
  <div class="col-sm-12 col-md-4">
    <div class="thumbnail">
      <%= link_to (image_tag project.image.url(:thumb)), project_path(project) %>
      <div class="caption">
        <h3><%= link_to project.name.truncate(20), project_path(project) %></h3>
        <p><%= t("crowdfunding_projects.budget") %>: <%= project.budget %> сом</p>
        <p><%= t("crowdfunding_projects.budget_donated") %>: <%= project.budget_donated %> сом</p>
        <div class="progress">
          <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= project.donation_ratio %>%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"> <%= project.donation_ratio.to_i %>
            %
          </div>
        </div>
        <% if project.deadline >= Time.now %>
            <p><%= t("crowdfunding_projects.deadline") %>:
              <p style="color: #cc0000"><%= number_of_days_till_deadline(project) %></p>
            </p>
        <% else %>
            <p>
              <%= t("crowdfunding_projects.expired_donated_time") %>
            </p>
        <% end %>
        <p><%= link_to t("crowdfunding_projects.more"), project_path(project), :class => "btn btn-primary btn-center" %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= tinymce %>

web-app/app/views/projects/_project_member_table.html.erb
<div class='container-fluid'>
  <p> Участники Проекта </p>
  <table id="member_table" class="table table-bordered table-condensed table-sm">
    <thead>
      <tr>
        <th>ФИО</th>
        <th>Роль</th>
        <th>Юзер</th>
        <th>Резюме</th>
        <th>      </th>
      </tr>
    </thead>
    <tbody>
      <% for project_members in @project.project_members %>
        <tr>
          <% if policy(project_members).edit? %>
            <td><%= link_to project_members.name, edit_project_project_member_path(@project, project_members), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></td>
          <% else %>
            <td><%= project_members.name %></td>
          <% end %>
          <td><%= project_members.role %></td>
          <% unless project_members.user.blank? %>
            <td><%= project_members.user.name %></td>
          <% else %>
            <td>Пусто</td>
          <% end %>
          <% unless project_members.resume.blank? %>
            <td><%= link_to 'CV', project_members.resume.url, download: 'CV' %></td>
          <% else %>
            <td>Пусто</td>
          <% end %>
          <% if policy(project_members).destroy? %>
            <td><%= link_to 'Удалить', project_project_member_path(@project,project_members), method: :delete, :remote=>false, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

web-app/app/views/projects/edit.html.erb
<h1>Изменение проекта</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
<%= tinymce %>

web-app/app/views/projects/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Краудфандинг</h1>
    <p class="lead">Вы можете поддержать любой стартап, перечислив средства на мобильный кошелек проекта</p>
  </div>
</div>

<%= render 'list', projects: @projects %>
<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=ecd4gg%40gmail.com&amp;color=%231B887A&amp;src=eqfqjnf3og0vjsr2gbdbgfqpio%40group.calendar.google.com&amp;color=%230F4B38&amp;src=ops.bishkek%40gmail.com&amp;color=%23691426&amp;ctz=Asia%2FBishkek" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

<%= paginate @projects %>

<%= link_to 'New Project', new_project_path %>

web-app/app/views/projects/new.html.erb
<h1>Создание нового проекта</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

<%= tinymce %>

web-app/app/views/projects/show.html.erb
<%= tinymce %>

<div class='container'>
  <div class='row'>
    <div class="col-xs-12 col-md-5 col-md-offset-1">
      <%= image_tag @project.image.url(:medium) %><br>
    </div>
    <div class="col-xs-12 col-md-5">
      <h1><%= @project.name %></h1>
      <p>Категория: <%= @project.category.name %></p>
      <p>Стадия: <%= @project.stage %></p>
      <p>Статус: <%= @project.status %></p>
      <p>Дата окончания сбора средств: <%= @project.deadline %></p>
      <p>Бюджет проекта: <%= @project.budget %> сом</p>
      <p>Собранный бюджет: <%= @project.budget_donated %> сом</p>
      <% budget_progress = ((@project.budget_donated.to_f / @project.budget.to_f)*100).to_f.round %><br>
      <div class="progress">
        <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= budget_progress %>%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"> <%= @project.donation_ratio %>
          %
        </div>
      </div>
      <% if @project.deadline >= Time.now %>
          <p>
            До окончания сбора средств осталось: <br>
            <strong style="color: #cc0000"><%= number_of_days_till_deadline(@project) %></strong>
          </p>
      <% else %>
          <p>
            Время сбора средсв истекло
          </p>
      <% end %>
      <p>Мобильный кошелек: <%= @project.account %></p>
      <%= link_to "Перечислить средства", user_info_request_project_mobilnik_payments_path(@project), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', :class => "btn btn-success"}%>
      <% if user_signed_in? && current_user.superadmin? %>
        <%= link_to "Вернуть средства", admin_phone_number_request_project_mobilnik_payments_path(@project), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', :class => "btn btn-success"}%>
      <% end %>
      <%= render 'project_member_table' %>
      <% if policy(@project.project_members).create? %>
        <%= link_to "Добавить участника проекта", new_project_project_member_path(@project), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', :class => "btn btn-info"} %>
      <% end %>
    </div>
  </div>
  <br>
  
  <div class="row">
    <div class='col-xs-12 col-md-10 col-md-offset-1'>
      <h2>Описание проекта</h2>
      <p><%= raw @project.description %></p>
      <h2>Бюджет проекта</h2>
      <p><%= raw @project.budget_description %></p>
      <h2>Комментарий автора</h2>
      <p><%= raw @project.author_comment %></p>
      <% if @project.status == 'Неактивный' %>
          <h2>Причина отмены проекта</h2>
          <p><%= raw @project.cancel_reason %></p>
          <h2>Дата отмены проекта</h2>
          <p><%= @project.cancel_date %></p>
      <% end %>
    </div>
  </div>
</div><br>
<div class="modal fade" id="modal-window">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<%= nested_comments(@project.comments.arrange(:order => :created_at), @project) %>
<%= render partial: "comments/form", locals: {commentable: @project} %>
<% if user_signed_in? %>
    <% if !subscribed_email?(@project) %>
        <%= render "subscribed_mails/form", subscribed_mail: @subscribed_mail %>
    <% else %>
        <%= link_to 'Unsubscribe', subscribed_mail_path(email_unsubscribe), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default' %>
    <% end %>
<% end %> <br>
<% if policy(@project).create? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %> |
  <%= link_to 'Destroy', project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<div id="modal-window" class="modal hide fade" role="dialog" aria-hidden="true"></div>