web-app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  get '/feedbacks/new'
  post '/feedbacks/create'
  get 'user_projects/index'

  resources :incubators
  post '/tinymce_assets' => 'tinymce_assets#create'

  devise_for :users
  ActiveAdmin.routes(self)

  resources :projects do
    resources :comments, module: :projects
    resources :project_members
    resources :mobilnik_payments do
      collection do
        get 'user_info_request'
        get 'admin_phone_number_request'
        get 'mobilnik_code_request'
        get 'mobilnik_token_request'
        get 'mobilnik_code_request_for_admin'
        get 'mobilnik_token_request_for_admin'
      end
    end
  end
  
  resources :categories
  resources :subscribed_mails
  resources :incubators
  
  authenticate :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'projects#index'
end

web-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  
  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :occupation, :work_experience,
                                                         :country, :region, :age])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :occupation, :work_experience,
                                                         :country, :region, :age])
    end

    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end

    def access_denied(exception)
      flash[:danger] = exception.message
      redirect_to root_url
    end
    
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(root_url)
    end

  protected 
    def after_sign_up_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || super
    end
end

web-app/app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name].join(", ")
      end
    end
  end 

	def budget_progress(project)
		((project.budget_donated.to_f / project.budget.to_f)*100).to_f.round
	end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("project_members_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

web-app/app/views/layouts/application/_filter.html.erb
<div class="row">
  <div class="crowdfunding_projects_filter">
    <%= form_for_filterrific @filterrific, :html => {:class => 'form-inline'} do |f| %>
      <div class="form-group col-xs-12 col-md-3">
        <h4><%= t("crowdfunding_projects.status") %></h4>
        <%= f.check_box(:with_status, {multiple: true}, t("crowdfunding_projects.active"), nil) %><%= t("crowdfunding_projects.active") %>
        <%= f.check_box(:with_status, {multiple: true}, t("crowdfunding_projects.inactive"), nil) %><%= t("crowdfunding_projects.inactive") %>
      </div>
      <div class="form-group col-xs-12 col-md-3">
        <h4><%= t("crowdfunding_projects.category") %></h4>
        <% Category.all.each do |category| %>
            <%= f.check_box(:with_category, {multiple: true}, category.id, nil) %> <%= category.name %>
        <% end %>
      </div>

      <div class="form-group col-xs-12 col-md-3">
        <h4><%= t("crowdfunding_projects.sorting") %></h4>
        <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {:class => 'form-control'}) %>
      </div>
      <div class="form-group col-xs-12 col-md-3">
        <%= submit_tag t("crowdfunding_projects.submit"), class: 'btn btn-default crowdfunding_btn' %>
      </div>
    <% end %>
  </div>
</div>

web-app/app/views/layouts/application/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container padding_top">
		<p>Номер телефона: 937 99 92</p>

		<p>Email: superadmin@example.com</p>

  </div>
</nav>

web-app/app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= t "site_name" %></a>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <%= nav_to t("navigation.crowdfunding_projects"), :projects, title: t("navigation.crowdfunding_projects") %>
        <%= nav_to t("navigation.startup_forum"), :incubators, title: t("navigation.startup_forum") %>
        <% if user_signed_in? %>
          <%= nav_to t("navigation.my_projects"), user_projects_index_path, title: t("navigation.user_projects") %>
        <% end %>
        <%= nav_to t("navigation.contacts"), feedbacks_new_path, title: t("navigation.contacts") %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown account_block">
            <%= link_to current_user.name.capitalize, edit_user_registration_path(current_user) %>
          </li>
          <% if current_user.role == 'superadmin' %>
            <li><%= link_to 'Админ', admin_root_path %></li>
          <% end %>
          <li class="dropdown account_block">
            <%= link_to 'Выход', destroy_user_session_path %>
          </li>
        <% else %>
          <%= nav_to t("account.sign_up"), new_user_registration_path, title: t("account.sign_up") %>
          <%= nav_to t("account.sign_in"), new_user_session_path, title: t("account.sign_in") %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>