web-app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  get '/feedbacks/new'
  post '/feedbacks/create'
  get 'user_projects/index'

  resources :incubators
  post '/tinymce_assets' => 'tinymce_assets#create'

  devise_for :users
  ActiveAdmin.routes(self)

  resources :projects do
    resources :comments, module: :projects
    resources :project_members
    resources :mobilnik_payments do
      collection do
        get 'user_info_request'
        get 'admin_phone_number_request'
        get 'mobilnik_code_request'
        get 'mobilnik_token_request'
        get 'mobilnik_code_request_for_admin'
        get 'mobilnik_token_request_for_admin'
      end
    end
  end
  
  resources :categories
  resources :subscribed_mails
  resources :incubators
  
  authenticate :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'projects#index'
end

web-app/app/models/incubator.rb
class Incubator < ApplicationRecord

  has_attached_file :image,
                    styles: { medium: '400x400>', thumb: '300x300>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']


end

web-app/app/controllers/incubators_controller.rb
class IncubatorsController < InheritedResources::Base

  private

    def incubator_params
      params.require(:incubator).permit(:name, :image)
    end
end

web-app/app/helpers/incubators_helper.rb
module IncubatorsHelper
end

web-app/app/views/incubators/_form.html.erb
<div class = 'container'>
  <div class = 'row'>
    <div class ='col-md-6 col-md-offset-3'>
		<%= simple_form_for(@incubator) do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <%= f.input :name %>
		  </div>
		  <div class="form-inputs">
		  	<%= f.file_field :image %>
		  </div>

		  <div class="form-actions">
		    <%= f.button :submit %>
		  </div>


		<% end %>
    </div>
  </div>
</div>

web-app/app/views/incubators/edit.html.erb
<h1>Изменить инкубатор</h1>

<%= render 'form', incubator: @incubator %>

<%= link_to 'Show', @incubator %> |
<%= link_to 'Back', incubators_path %>

web-app/app/views/incubators/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Стартап инкубаторы</h1>
    <p class="lead">Подайте заявку в один из стартап инкубаторов, и мы поможем воплотить вашу идею в успешный бизнес</p>
  </div>
</div>

<div class="row crowdfunding_projects">
  <% @incubators.each do |incubator| %>
    <div class="col-sm-12 col-md-4">
      <div class="thumbnail">
        <%= link_to (image_tag incubator.image.url(:thumb)), incubator %><br>
        <div class="caption">
          <%= link_to incubator.name, incubator %><br>
        </div> 
      </div>
    </div>
  <% end %>
</div>

web-app/app/views/incubators/new.html.erb
<h1>Новый инкубатор</h1>

<%= render 'form', incubator: @incubator %>

<%= link_to 'Back', incubators_path %>

web-app/app/views/incubators/show.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3"><%= @incubator.name %></h1>
    <p class="lead">Добро пожаловать в нашу дружную команду профессионалов!</p>
  </div>
</div>


<%= link_to 'Back', incubators_path %>